### PR TITLE
Added link to tutorial

### PR DESCRIPTION
**Pull request by rohitchormale**
Nice tutorial for beginners

### CODE REVIEW

**Comment by lirantal** [comment]
A bit out dated now?

**Comment by idvoretskyi** [comment]
@lirantal why do you feel that the proposed tutorial is outdated?

**Comment by lirantal** [comment]
I'm not opposed.
I didn't proof-read it but I noticed first thing the title which shows the last update was May 2015.

**Comment by wsargent** [comment]
Closing -- the link is a tutorial on Docker itself, not on Dockerfile (which is where it is listed).  The cheat sheet presupposes that people have looked at tutorials already and need a reference, which the linked article doesn't help with.

**Pull request closed without merging**
