### PR TITLE
Replace Tutorials link 404

### PR DESCRIPTION
**Pull request by josephcjohnsonjr**
docs.docker.com/linux/started -> docs.docker.com/engine/getstarted

### CODE REVIEW

**Comment by wsargent** [comment]
I think the linux link is probably something more like https://docs.docker.com/v1.11/engine/installation/binaries/#get-the-linux-binaries -- the link you have points to a pre-release version and isn't linux specific.

**Comment by tomtruitt** [comment]
the tutorial doesn't suggest this should be linux specific. i just submitted the same PR because i didn't check first... not sure what the hold up is...

**Comment by wsargent** [comment]
@tomtruitt @josephcjohnsonjr the tutorial is listed under the Installation / Linux section, and was previously "docs.docker.com/linux/started" -- the goal is to have something that is a getting started tutorial for linux users.  

If this is a good link but it is not Linux specific, then it should be moved to another section out from under the Installation / Linux section.

**Comment by tomtruitt** [comment]
https://docs.docker.com/engine/getstarted/ is the link to "Getting Started with Docker". i suppose if you if that isn't good because it isn't linux specific then https://docs.docker.com/engine/installation/ starts off with links for various linux distros (but also finishes with links for other OS's)

**Comment by tomtruitt** [comment]
but you already have a link to installation instructions immediately preceeding this one.. i thought this link is for the getting started tutorials provided by docker.

**Comment by tomtruitt** [comment]
This tutorial is designed as a getting started with Docker, and works the same whether you are using Docker for Mac, Docker for Windows, Docker on Linux, or Docker Toolbox (for older Mac and Windows systems).

**Comment by wsargent** [comment]
@tomtruitt Okay.  You see this link:

https://github.com/wsargent/docker-cheat-sheet#installation

There's one link in the Linux section: "If you are a complete Docker newbie, you should follow the series of tutorials now."

There's another link in the MacOS section: "If you are a complete Docker newbie, you should probably follow the series of tutorials now."

There are currently two different versions, pointing to two different links.  If you're saying they took out the OS specific guides, then take it out of both places and add a tutorial section.

**Comment by tomtruitt** [comment]
well it seems they still have an os specific guide or mac and windows...

**Comment by tomtruitt** [comment]
actually a on the third and fourth page of the generic getting started link it talks about how the learner is running linux software on a mac so i give up on this lol

**Pull request closed without merging**
