### PR TITLE
docs: add Simplified Chinese version 

### PR DESCRIPTION
**Pull request by geminiyellow**
add Simplified Chinese version.

### CODE REVIEW

**Comment by wsargent** [comment]
Hi @geminiyellow this looks great, and can you squash it down into a single commit?

**Comment by geminiyellow** [comment]
@wsargent ok, zipzipzip

**Comment by wsargent** [comment]
Thanks!

**Comment by wsargent** [comment]
@geminiyellow are you okay with being added as a contributor so you can merge your own commits to the chinese doc?

**Comment by geminiyellow** [comment]
@wsargent oh, my honor .

**Comment by wsargent** [comment]
@geminiyellow okay done!

**Pull request merged**
